### ISSUE TITLE
/config view doesnt work?

### ISSUE THREAD

**Issue by theluqmn** [GlyphLabs/Glyph#11]
**Describe the bug**
The application doesn't respond when using `/config view`

**To Reproduce**
Run the `/config view` command. Am not sure if it's because I dont have admin perms, however I do have a management role in the server @Prizmin is in.

**Expected behavior**
According to the code, it's supposed to return the configs for the particular server I ran the command on.

**Screenshots**
![image](https://github.com/PurpLabs/PurpBot/assets/75654558/7f52560f-f3dd-4efe-af13-8a61e63d59b1)

**Comment by thrzl** [comment]
should be fixed, can you test it again?

**Comment by theluqmn** [comment]
Alright it works now, thanks for the patch.
![image](https://github.com/PurpLabs/PurpBot/assets/75654558/204e4e89-7fe2-4bf7-bb3d-f847eb4fc06b)
